spring:
  application:
    name: bike-rental
  mvc:
    servlet:
      path: /bikerental
  datasource:
    url: jdbc:h2:mem:testdb2
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

server:
  port: 8089
